### ISSUE TITLE
Running on linux, all ssb links are empty

### ISSUE THREAD

**Issue by hardfire** [soapdog/patchfox#1]
I am trying to get patchfox running on linux and it somehow seems to work, apart from the fact that every "ssb:" link ends up on a page like this on firefox

![image](https://user-images.githubusercontent.com/513457/36294092-7d90fd00-1306-11e8-94f1-449911a715c1.png)

I made some changes to the setup.js so that it takes the right path urls (based on what i could figure out). https://github.com/hardfire/patchfox/commit/e5c9321ba1b9a8ab71614f3453d319bae86610e4

Here's what the log looks like when i run `node server.js` and try to access a url via localhost:3013

```
...
        sqsum: 3380082.25 } } }
Connected post.tableflip.io:8008:@YXquIbh1OqCCdMuqCO4tSJuYR7RL811CTuu59n7G0pk=.ed25519
**************************........................ (indexes:100%, ooo:100%, ebt:50.2%)EBT failed, fallback to legacy { message: 'method:ebt,replicate is not on whitelist',
  name: 'Error',
  stack: 'Error: method:ebt,replicate is not on whitelist\n    at Function.perms.pre (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/permissions.js:88:14)\n    at Object.<anonymous> (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/local-api.js:35:21)\n    at PacketStreamSubstream.stream.read (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:67:23)\n    at PacketStream._onstream (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:230:11)\n    at PacketStream.write (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:135:41)\n    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:56:15\n    at /usr/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:24:37\n    at /usr/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11\n    at Object.cb (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:111:11)\n    at drain (/usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)' }
replication ended: @YXquIbh1OqCCdMuqCO4tSJuYR7RL811CTuu59n7G0pk=.ed25519 Error: method:ebt,replicate is not on whitelist
    at Function.perms.pre (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/permissions.js:88:14)
    at Object.<anonymous> (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/local-api.js:35:21)
    at PacketStreamSubstream.stream.read (/usr/lib/node_modules/scuttlebot/node_modules/muxrpc/stream.js:67:23)
    at PacketStream._onstream (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:230:11)
    at PacketStream.write (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream/index.js:135:41)
    at /usr/lib/node_modules/scuttlebot/node_modules/muxrpc/pull-weird.js:56:15
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-stream/sinks/drain.js:24:37
    at /usr/lib/node_modules/scuttlebot/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/usr/lib/node_modules/scuttlebot/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/usr/lib/node_modules/scuttlebot/node_modules/pull-reader/index.js:39:14)
```

any ideas? :D

**Comment by soapdog** [comment]
@hardfire are you running patchwork at the same time?

**Comment by hardfire** [comment]
@soapdog no! patchwork is not running.

**Comment by soapdog** [comment]
I haven't tested in Linux yet, will do it in the next couple days and get back to you.

**Comment by soapdog** [comment]
@hardfire I am making a ton of changes. Whatever was happening before should not be happening now.

**Comment by hardfire** [comment]
@soapdog awesome! I will test this in the coming days and let you know.

**Comment by soapdog** [comment]
Closing this because I am rewriting everything. It is a new codebase and whatever was happening shouldn't happen anymore.
