### ISSUE TITLE
linux 64 bit patchfox-2022.9.2-alpha can't start up

### ISSUE THREAD

**Issue by decentral1se** [soapdog/patchfox#149]
debian 11, running `patchfox-2022.9.2-alpha` [Patchfox for Linux (64bits)](https://github.com/soapdog/patchfox/releases/download/v2022.9.2-alpha/Patchfox-2022.9.2-alpha.tar.gz)). Saw:

```
./patchfox
error loading sodium bindings: No native build was found for platform=linux arch=x64 runtime=electron abi=103 uv=1 libc=glibc node=16.13.2 electron=18.2.3
    loaded from: /home/decentral1se/programs/patchfox-2022.9.2-alpha/resources/app.asar/node_modules/sodium-native

falling back to javascript version.
Gtk-Message: 19:48:30.361: Failed to load module "xapp-gtk3-module"
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
[7756:0909/194830.738463:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
{
  preferences: {
    theme: 'light',
    textSize: 'prose-lg',
    limit: '40',
    defaultIdentity: '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519'
  },
  MessageTypes: {
    vote: 'friends',
    pub: 'hide',
    private: 'hide',
    channel: 'friends',
    post: 'all',
    blog: 'all',
    contact: 'following',
    about: 'all',
    gathering: 'all'
  },
  '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519': {
    curve: 'ed25519',
    public: 'i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519',
    private: 'EtW50ue/MesVzvcP8Q7iwGtiyCvV0EU0LTVv8KBecSmLw5e1NhorQ+sXTTal3i+leauWD3wCztkxocYqheLF0w==.ed25519',
    id: '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519',
    remote: 'net:127.0.0.1:8008~shs:i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=',
    type: 'nodejs-db1',
    startServer: true
  }
}
preferences exist
{
  preferences: {
    theme: 'light',
    textSize: 'prose-lg',
    limit: '40',
    defaultIdentity: '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519'
  },
  MessageTypes: {
    vote: 'friends',
    pub: 'hide',
    private: 'hide',
    channel: 'friends',
    post: 'all',
    blog: 'all',
    contact: 'following',
    about: 'all',
    gathering: 'all'
  },
  '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519': {
    curve: 'ed25519',
    public: 'i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519',
    private: 'EtW50ue/MesVzvcP8Q7iwGtiyCvV0EU0LTVv8KBecSmLw5e1NhorQ+sXTTal3i+leauWD3wCztkxocYqheLF0w==.ed25519',
    id: '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519',
    remote: 'net:127.0.0.1:8008~shs:i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=',
    type: 'nodejs-db1',
    startServer: true
  }
}
default identity {
  remote: 'net:127.0.0.1:8008~shs:i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=',
  type: 'nodejs-db1',
  startServer: true,
  keys: {
    public: 'i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519',
    private: 'EtW50ue/MesVzvcP8Q7iwGtiyCvV0EU0LTVv8KBecSmLw5e1NhorQ+sXTTal3i+leauWD3wCztkxocYqheLF0w==.ed25519',
    id: '@i8OXtTYaK0PrF002pd4vpXmrlg98As7ZMaHGKoXixdM=.ed25519',
    curve: 'ed25519'
  }
}
error, probably no default identity Error: /tmp/.org.chromium.Chromium.NaFcGi: invalid ELF header
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/home/decentral1se/programs/patchfox-2022.9.2-alpha/resources/app.asar/node_modules/leveldown/node_modules/node-gyp-build/index.js:20:10)
    at Object.<anonymous> (/home/decentral1se/programs/patchfox-2022.9.2-alpha/resources/app.asar/node_modules/leveldown/binding.js:1:43) {
  code: 'ERR_DLOPEN_FAILED'
}
Error: /tmp/.org.chromium.Chromium.NaFcGi: invalid ELF header
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/home/decentral1se/programs/patchfox-2022.9.2-alpha/resources/app.asar/node_modules/leveldown/node_modules/node-gyp-build/index.js:20:10)
    at Object.<anonymous> (/home/decentral1se/programs/patchfox-2022.9.2-alpha/resources/app.asar/node_modules/leveldown/binding.js:1:43) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by JakeTrock** [comment]
have you tried `sudo apt install xapp`?
